version: '3'
services:

    flask_container:
        image: flask_image:1.0
        container_name: flask_container
        command: python3 /opt/flask_project/start
        environment:
            - PASSWORD=admin
        ports:
            - "9999:9999"
        volumes:
            - ../:/opt/flask_project
